[build]
  command = "pip install -r requirements.txt"
  publish = "ui/assets"
  functions = "functions"

[dev]
  framework = "#custom"
  targetPort = 8050
  port = 8888
  command = "python ui/landing_page.py"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
